USE_COLS = {
    "training": [
        "stId",
        "arsId",
        "busRouteId",
        "mkTm",
        "staOrd",
        "vehId1",
        "exps1",
        "arrmsg1",
        "reride_Num1",
        "rerdie_Div1",
    ],
    "analysis": [
        "stId",
        "stNm",
        "arsId",
        "busRouteId",
        "busRouteAbrv",
        "mkTm",
        "staOrd",
        "vehId1",
        "exps1",
        "arrmsg1",
        "reride_Num1",
        "rerdie_Div1",
    ],
    "traveltime": [
        "stId",
        "arsId",
        "busRouteId",
        "mkTm",
        "staOrd",
        "vehId1",
        "exps1",
        "arrmsg1",
        "reride_Num1",
    ],
}

FINAL_COLS = {
    "training": [
        # 원본/식별
        "mkTm",
        "busRouteId",
        "stId",
        "arsId",
        "staOrd",
        "vehId1",
        # 원본 기반 현재 정보
        "exps1",
        "arrmsg1",
        "remaining_seat",
        "full_flag",
        # 시간 파생
        "year",
        "month",
        "day",
        "hour",
        "minute",
        "dayofweek",
        "is_weekend",
        "is_holiday",
        "is_peak",
        "month_sin",
        "month_cos",
        "day_sin",
        "day_cos",
        "hour_sin",
        "hour_cos",
        "minute_sin",
        "minute_cos",
        "dow_sin",
        "dow_cos",
        # 날씨 데이터
        "precipitation",
        "fog",
        "temperature",
        "rainfall",
    ],
    "analysis": [
        # 원본/식별
        "mkTm",
        "station_name",
        "busRouteId",
        "route_name",
        "stId",
        "arsId",
        "staOrd",
        "vehId1",
        # 원본 기반 현재 정보
        "exps1",
        "arrmsg1",
        "remaining_seat",
        "full_flag",
        # 좌석 파생
        "congestion_level",
        # 이전 좌석수 정보
        "prev_seat",
        "seat_diff",
        # trip_id
        "trip_id",
        # 시간 파생
        "date",
        "year",
        "month",
        "day",
        "hour",
        "minute",
        "dayofweek",
        "is_weekend",
        "is_holiday",
        "is_peak",
        # 날씨 데이터
        "precipitation",
        "fog",
        "temperature",
        "rainfall",
    ],
    "traveltime": [
        # 원본/식별
        "mkTm",
        # 여행 시간
        "arrival_time",
        # 원본/식별 - 이어서
        "busRouteId",
        "stId",
        "arsId",
        "staOrd",
        "vehId1",
        "travel_time",
    ],
}

NUMERIC_COLS = {
    "training": [
        "staOrd",
        "exps1",
        "remaining_seat",
        "full_flag",
        "year",
        "month",
        "day",
        "hour",
        "minute",
        "dayofweek",
        "is_weekend",
        "is_holiday",
        "is_peak",
        "month_sin",
        "month_cos",
        "day_sin",
        "day_cos",
        "hour_sin",
        "hour_cos",
        "minute_sin",
        "minute_cos",
        "dow_sin",
        "dow_cos",
        # 날씨 데이터
        "precipitation",
        "fog",
        "temperature",
        "rainfall",
    ],
    "analysis": [
        "staOrd",
        "exps1",
        "remaining_seat",
        "full_flag",
        "year",
        "month",
        "day",
        "hour",
        "minute",
        "dayofweek",
        "is_weekend",
        "is_holiday",
        "is_peak",
        # 날씨 데이터
        "precipitation",
        "fog",
        "temperature",
        "rainfall",
        # 이전 좌석수 정보
        "prev_seat",
        "seat_diff",
    ],
    "traveltime": [
        "staOrd",
        # 여행 시간 관련
        "travel_time",
    ],
}
